# Generated by Django 4.1.2 on 2022-10-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_alter_author_name_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['author'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
