# Generated by Django 4.1.2 on 2022-10-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0003_alter_book_options_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
