# Generated by Django 4.1.2 on 2022-10-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0004_alter_book_options_alter_book_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
